//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Mvc.Data
{
    using Coop.Mvc.Entity;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MessagesEntities : DbContext
    {
        public MessagesEntities()
            : base("name=MessagesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessToken> AccessTokens { get; set; }
        public DbSet<AdminAccount> AdminAccounts { get; set; }
        public DbSet<College> Colleges { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<DownloadableForm> DownloadableForms { get; set; }
        public DbSet<InboundSM> InboundSMS { get; set; }
        public DbSet<LoanAmountMatrix> LoanAmountMatrices { get; set; }
        public DbSet<LoanApplication> LoanApplications { get; set; }
        public DbSet<LoanType> LoanTypes { get; set; }
        public DbSet<NewsAndAnnouncement> NewsAndAnnouncements { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<RegDump> RegDumps { get; set; }
        public DbSet<RelativeEmployee> RelativeEmployees { get; set; }
        public DbSet<ShareCapital> ShareCapitals { get; set; }
        public DbSet<ShareCapitalPayment> ShareCapitalPayments { get; set; }
        public DbSet<UnconfirmedLoan> UnconfirmedLoans { get; set; }
        public DbSet<UnconfirmedUser> UnconfirmedUsers { get; set; }
        public DbSet<UserBeneficiary> UserBeneficiaries { get; set; }
        public DbSet<UserDetail> UserDetails { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
