//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Mvc.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class College
    {
        public int CollegeID { get; set; }
        public string CollegeName { get; set; }
    }
}
