//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Mvc.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboundSM
    {
        public int RecordID { get; set; }
        public Nullable<System.DateTime> MsgDateTime { get; set; }
        public string DestinationAddress { get; set; }
        public string MessageId { get; set; }
        public string Message { get; set; }
        public string ResourceURL { get; set; }
        public string SenderAddress { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<bool> IsRead { get; set; }
    }
}
