//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Mvc.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplication
    {
        public int TransactionID { get; set; }
        public string EmpNo { get; set; }
        public string CoMakerEmpNo { get; set; }
        public string TypeOfLoan { get; set; }
        public string Reason { get; set; }
        public decimal Amount { get; set; }
        public int NoOfMonths { get; set; }
        public Nullable<bool> Confirmed { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public string CoMaker2EmpNo { get; set; }
        public Nullable<bool> Done { get; set; }
        public Nullable<bool> Declined { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string PayslipPath { get; set; }
    }
}
