//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Mvc.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanAmountMatrix
    {
        public int RecordID { get; set; }
        public int LoanType { get; set; }
        public double LoanAmount { get; set; }
        public double RequiredShareCapital { get; set; }
        public double Interest { get; set; }
        public int MonthsPayable { get; set; }
        public Nullable<double> ProcessingFee { get; set; }
    }
}
