//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Mvc.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int RecordID { get; set; }
        public int TransactionID { get; set; }
        public double PayAmount { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
    }
}
