//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Mvc.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnconfirmedLoan
    {
        public int TransactionID { get; set; }
        public Nullable<bool> ConfirmedByMaker { get; set; }
        public Nullable<bool> ConfirmedByCoMaker { get; set; }
        public System.DateTime DateFiled { get; set; }
        public string ConfirmCodeMakerSMS { get; set; }
        public string ConfirmCodeCoMakerSMS { get; set; }
        public string ConfirmCodeMakerEmail { get; set; }
        public string ConfirmCodeCoMakerEmail { get; set; }
        public Nullable<bool> ConfirmedByCoMaker2 { get; set; }
        public string ConfirmCodeCoMaker2SMS { get; set; }
        public string ConfirmCodeCoMaker2Email { get; set; }
    }
}
