//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Mvc.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBeneficiary
    {
        public int RecordID { get; set; }
        public string EmpNo { get; set; }
        public string BeneficiaryName { get; set; }
        public System.DateTime DOB { get; set; }
    }
}
