//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coop.Mvc.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int RecordID { get; set; }
        public string EmpNo { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string College { get; set; }
        public string Dept { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public string MemberStatus { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public string Picture { get; set; }
        public string ATMAccountNo { get; set; }
        public string TINNo { get; set; }
        public string SSSNo { get; set; }
        public string Gender { get; set; }
        public string CivilStatus { get; set; }
        public string FatherName { get; set; }
        public string FatherOccupation { get; set; }
        public string MotherName { get; set; }
        public string MotherOccupation { get; set; }
        public string LegalSpouse { get; set; }
        public string SpouseEmployer { get; set; }
        public string BusinessName { get; set; }
        public string BusinessAddress { get; set; }
        public string OtherSourceOfIncome { get; set; }
        public string EmergencyName { get; set; }
        public string EmergencyAddress { get; set; }
        public string EmergencyNumber { get; set; }
    }
}
